routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'eloquent', 'as' => 'eloquent.'], function () {
    Route::get('clients', 'EloquentClientsController@index')->name('client.list');
    Route::get('client/create', 'EloquentClientsController@create')->name('client.create');
    Route::post('client/save', 'EloquentClientsController@store')->name('client.store');
    Route::get('client/delete/{id}', 'EloquentClientsController@delete')->name('client.delete');
});

Route::group(['prefix' => '', 'as' => 'site.'], function () {
    /* Usando controllers - 'Controller@action' */
    Route::get('client', 'SiteClientsController@create');
    Route::post('client/save', 'SiteClientsController@store')->name('client.store');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    /* Usando controllers - 'Controller@action' */
    Route::get('client', 'ClientsController@create');
    Route::post('client/save', 'ClientsController@store')->name('client.store');
});





/*
Route::get('client', function () {
    return view('client');
});

Route::post('client', function (\Illuminate\Http\Request $request) {
//    return $request->get('value');
//    var_dump(json_encode($_POST));
    $posted = json_encode($request->all());
    return "Dados Postados pelo formulario_csrf: <hr/> {$posted}";
})->name('client.store');

Route::get('client/{id}/{name?}', function ($id, $name = 'Jesus Cristo') {

    return view('client-name')
        ->with('id', $id)
        ->with('name', $name);

//    return view('client-name',[
//       'id'=>$id,
//       'name'=>$name
//    ]);


});

Route::get('if-for', function () {
    return view('if-for');
});*/


//Route::get('minharota',function(){
//    return 'Minha Rota';
//});
//
//Route::get('minharotafake.php',function(){
//    return 'Minha Rota Fake.php';
//});
//
//// {param}, {paramOpcional?}
//Route::get('client/{id}/{name?}', function($id,$name="Emílio"){
//    echo $id . ' = '. $name;
//});
//
//Route::get('formulario_csrf',function (){
//
//    $csrf_token = csrf_token();
//
//    $html = <<<HTML
//    <html>
//        <body>
//            <form action="/formulario_csrf" method="post">
//                <input type="hidden" name="_token" value="{$csrf_token}" />
//                <input type="text" name="value" />
//                <button type="submit">Enviar</button>
//            </form>
//        </body>
//    </html>
//HTML;
//
//   return $html;
//
//});
//
//Route::post('formulario_csrf',function(\Illuminate\Http\Request $request){
////    var_dump(json_encode($_POST));
//    $posted = json_encode($request->all());
//    return "Dados Postados pelo formulario_csrf: <hr/> {$posted}";
//})->name('client.store');
//
//// Rotas nomeadas
//Route::get('formulario2',function (){
//
//    $csrf_token = csrf_token();
//    $action = route('client.store');
//
//    $html = <<<HTML
//    <html>
//        <body>
//            <form action="{$action}" method="post">
//                <input type="hidden" name="_token" value="{$csrf_token}" />
//                <input type="text" name="value" />
//                <button type="submit">Enviar</button>
//            </form>
//        </body>
//    </html>
//HTML;
//
//    return $html;
//
//});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = ['name', 'address'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClientsController extends Controller
{
    //
    public function create(){
        return view('admin.clients.client');
    }

    public function store(Request $request){
        return $request->get('value');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EloquentClientsController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class EloquentClientsController extends Controller
{
    public function index(){
        $clients = Client::all();

        return view('eloquent.clients',[
            'clients'=>$clients
        ]);

    }

    //
    public function create(){
        return view('eloquent.create');
    }

    public function store(Request $request){

        $client = new Client();

        $client::create($request->all());

        return redirect()->route('eloquent.client.list');

    }

    public function delete(Request $request, $id){

        $client = new Client();
        $client::destroy($id);

        return redirect()->route('eloquent.client.list');
    }
}

app/Http/Controllers/SiteClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiteClientsController extends Controller
{
    //
    public function create(){
        return view('site.client');
    }

    public function store(Request $request){
        return $request->get('value');
    }
}

resources/views/admin/clients/client.blade.php
<html>
    <body>
    <h3>Site do ADM</h3>
        <form action="{{ route('admin.client.store') }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <input type="text" name="value"/>
            <button type="submit">Enviar</button>
        </form>
</body>

resources/views/client-name.blade.php
<p>Cliente: <?php echo $id; ?> - <?php echo $name; ?></p>

<p>{{ 2+2 }}</p>
<p>{{ $name . " Diniz" }}</p>
<p>{{ isset($conteudo) ? $conteudo : "Variável não existe" }}</p>
<p>{{ $conteudo or "Variável não existe" }}</p>
<p>{{ "<a href='#'>Link</a>" }} -> htmlentities() ou Interpolação escaped </p>
<p>{!! "<a href='#'>Link</a>" !!} -> Interpolação unescaped</p>

resources/views/client.blade.php
<html>
    <body>
        <form action="{{ route('client.store') }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <input type="text" name="value"/>
            <button type="submit">Enviar</button>
        </form>
</body>

resources/views/eloquent/clients.blade.php
<h3>Eloquent Clientes</h3>

<a href="{{ route('eloquent.client.create') }}">Cadastrar</a><br><br>

<table border="1">
    <thead>
        <tr>
            <th>#</th>
            <th>name</th>
            <th>address</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($clients as $client)
            <tr>
                <td>{{ $client->id }}</td>
                <td>{{ $client->name }}</td>
                <td>{{ $client->address }}</td>
                <td align="center">
                    <a class="btn-delete" href="#" data-name="{{ $client->name }}" data-href="{{ route('eloquent.client.delete',['id'=>$client->id]) }}" data-object="{{ $client->toJson()  }}">Delete</a>
                </td>
            </tr>
        @endforeach
    </tbody>

</table>

<script>

    document.addEventListener('DOMContentLoaded',function(){

        var allbtn = document.getElementsByClassName('btn-delete');

        Array.prototype.forEach.call(allbtn,function(elem){

            let name = elem.dataset.name;
            let url = elem.dataset.href;
            let clientJSON = JSON.parse(elem.dataset.object);

            elem.onclick = function(){

                if( window.confirm('Deseja realmente excluir registro '+ clientJSON.id +' - '+clientJSON.name +'?') ){
                    location.href = url;
                }

            }
        });
    });

</script>

resources/views/eloquent/create.blade.php
    <html>
<body>
<h3>Eloquent - Cadastrar Clientes</h3>



<form action="{{ route('eloquent.client.store') }}" method="post">

    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>

    <label for="name">Nome</label>
    <input type="text" name="name" id="name"/>

    <label for="address">Endereço</label>
    <input type="text" name="address" id="address"/>

    <button type="submit">Enviar</button>

</form>

<a href="{{ route('eloquent.client.list') }}">Voltar</a><br><br>
</body>

resources/views/if-for.blade.php
<?php $num = 20; ?>

<!-- uso do '@'  para Estruturas lógicas-->
@if($num < 20)
    <p>Número é menor que vinte</p>
@elseif($num==20)
    <p>Número é igual a vinte</p>
@else
    <p>Número é Maior que vinte</p>
@endif



<?php $k = 0; ?>

{{ "WHILE" }}
@while($k < 20)
    <p>Valor: {{ $k }}</p>
    <?php $k++ ?>
@endwhile

{{ "FOREACH" }}
<?php $array = [1,2,3,4,5]; ?>

@foreach($array as $value)
    <p>Chave {{ $loop->index }}, Valor: {{ $value }}</p>
@endforeach

{{ "FORELSE or ELSE FOREACH" }}
<?php $array = []; ?>

@forelse($array as $value)
    <p>Chave {{ $loop->index }}, Valor: {{ $value }}</p>
@empty
    <p>Nenhum elemento no array</p>
@endforelse

resources/views/site/client.blade.php
<html>
    <body>
        <h3>Site do Cliente</h3>
        <form action="{{ route('site.client.store') }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <input type="text" name="value"/>
            <button type="submit">Enviar</button>
        </form>
</body>